### ISSUE TITLE
Why my image load failed?

### ISSUE THREAD

**Issue by aashishdhawan** [hyperoslo/Imaginary#16]
I think we should show some kind of error in console if image loading fails in Fetcher. Otherwise user of this repo will keep guessing what went wrong and why his/her imageURL is not showing any image.

**Comment by zenangst** [comment]
Hey @aashishdhawan, this is a great suggestion. At the moment, `Imaginary` is a work in progress and has yet to hit `1.0` so we will probably add a lot of new stuff before it is ready to be released. I labeled this as `enhancement` so that we don't forget to evaluate and potentially included it in the future.

Thanks for support `Imaginary` and keep the suggestions coming if you have more :sunglasses:

**Comment by zenangst** [comment]
This issue is solved by https://github.com/hyperoslo/Imaginary/pull/34.
