### ISSUE TITLE
Best effort cache

### ISSUE THREAD

**Issue by Skorch** [hyperoslo/Imaginary#39]
I'm working on a use case where the app is available offline.  

Is it possible for the following scenario to be satisified?

1) I have images in my cache
2) images have an expiry set (default set by Imaginary)
3) I am offline after the image expires
4) Fetcher can't get image because it's offline so it uses the last known image, even though cache has expired.

Ideally, I'd want to have the images never expire, but the Fetcher check for an update every X days, in case the image has been modified for whatever reason.

Thanks!

**Comment by zenangst** [comment]
@Skorch hey man! Firstly, sorry for the late response.

So what you want is the cache cleanup to take online/offline status into account. When offline, don't perform cleanup as the app cannot get new images. I think this make a lot of sense. However, this is not up to this framework to decide, this is actually handled by [Cache](https://github.com/hyperoslo/Cache) that `Imaginary` uses for storing the images to disk.

Code reference: https://github.com/hyperoslo/Cache/blob/master/Source/Shared/Cache/CacheManager.swift#L120

I'm gonna go ahead and close this issue and open another one on `Cache` because that's where we need to add the feature :)

**Comment by zenangst** [comment]
Now that `Cache` supports opting out from doing automatic expiration cleanup, I think we can go ahead and make this configurable in `Imaginary`.

**Comment by onmyway133** [comment]
@Skorch `Imaginary 3` now allows you you to custom the fetching and storage to your liking https://github.com/hyperoslo/Imaginary#fetching
